FROM gcr.io/distroless/java21-debian12:nonroot

ENV TZ="Europe/Oslo"

WORKDIR /app

COPY spesialist-db-migrations/build/install/app/ /app/
ENTRYPOINT ["java", "-cp", "/app/lib/*", "no.nav.helse.spesialist.db.migrations.AppKt"]
CMD []
