package no.nav.helse.spesialist.application

import no.nav.helse.db.SessionContext

class InMemorySessionContext(
    override val annulleringRepository: InMemoryAnnulleringRepository,
    override val arbeidsforholdDao: UnimplementedArbeidsforholdDao,
    override val arbeidsgiverRepository: InMemoryArbeidsgiverRepository,
    override val automatiseringDao: UnimplementedAutomatiseringDao,
    override val avviksvurderingRepository: InMemoryAvviksvurderingRepository,
    override val behandlingRepository: InMemoryBehandlingRepository,
    override val commandContextDao: InMemoryCommandContextDao,
    override val dialogDao: DelegatingDialogDao,
    override val dialogRepository: InMemoryDialogRepository,
    override val dokumentDao: InMemoryDokumentDao,
    override val egenAnsattDao: DelegatingEgenAnsattDao,
    override val legacyBehandlingDao: UnimplementedLegacyBehandlingDao,
    override val legacyPersonRepository: DelegatingLegacyPersonRepository,
    override val legacyVedtaksperiodeRepository: DelegatingLegacyVedtaksperiodeRepository,
    override val meldingDao: InMemoryMeldingDao,
    override val metrikkDao: UnimplementedMetrikkDao,
    override val notatDao: DelegatingNotatDao,
    override val notatRepository: InMemoryNotatRepository,
    override val oppgaveDao: DelegatingOppgaveDao,
    override val oppgaveRepository: InMemoryOppgaveRepository,
    override val overstyringRepository: InMemoryOverstyringRepository,
    override val periodehistorikkDao: InMemoryDoNothingPeriodehistorikkDao,
    override val personDao: DelegatingPersonDao,
    override val personRepository: InMemoryPersonRepository,
    override val personPseudoIdDao: InMemoryPersonPseudoIdDao,
    override val påVentDao: DelegatingPåVentDao,
    override val påVentRepository: InMemoryPåVentRepository,
    override val reservasjonDao: InMemoryReservasjonDao,
    override val risikovurderingDao: UnimplementedRisikovurderingDao,
    override val saksbehandlerDao: DelegatingSaksbehandlerDao,
    override val saksbehandlerRepository: InMemorySaksbehandlerRepository,
    override val stansAutomatiskBehandlingDao: InMemoryStansAutomatiskBehandlingDao,
    override val stansAutomatiskBehandlingSaksbehandlerDao: UnimplementedStansAutomatiskBehandlingSaksbehandlerDao,
    override val sykefraværstilfelleDao: DelegatingSykefraværstilfelleDao,
    override val tildelingDao: UnimplementedTildelingDao,
    override val tilkommenInntektRepository: InMemoryTilkommenInntektRepository,
    override val totrinnsvurderingRepository: InMemoryTotrinnsvurderingRepository,
    override val utbetalingDao: UnimplementedUtbetalingDao,
    override val varselRepository: InMemoryVarselRepository,
    override val varseldefinisjonRepository: InMemoryVarseldefinisjonRepository,
    override val vedtaksperiodeRepository: InMemoryVedtaksperiodeRepository,
    override val vedtakBegrunnelseRepository: InMemoryVedtakBegrunnelseRepository,
    override val vedtakDao: UnimplementedVedtakDao,
    override val vergemålDao: UnimplementedVergemålDao,
    override val åpneGosysOppgaverDao: UnimplementedÅpneGosysOppgaverDao,
    override val midlertidigBehandlingVedtakFattetDao: InMemoryMidlertidigBehandlingVedtakFattetDao,
    override val vedtakRepository: VedtakRepository,
    override val opptegnelseRepository: OpptegnelseRepository
) : SessionContext
