package no.nav.helse.spesialist.application

import no.nav.helse.db.Daos

class InMemoryDaos(
    override val annulleringRepository: InMemoryAnnulleringRepository,
    override val arbeidsgiverApiDao: UnimplementedArbeidsgiverApiDao,
    override val behandlingApiRepository: UnimplementedBehandlingApiRepository,
    override val behandlingsstatistikkDao: UnimplementedBehandlingsstatistikkDao,
    override val commandContextDao: InMemoryCommandContextDao,
    override val definisjonDao: UnimplementedDefinisjonDao,
    override val dialogDao: DelegatingDialogDao,
    override val dokumentDao: InMemoryDokumentDao,
    override val egenAnsattDao: DelegatingEgenAnsattDao,
    override val egenAnsattApiDao: DelegatingEgenAnsattApiDao,
    override val legacyBehandlingDao: UnimplementedLegacyBehandlingDao,
    override val legacyVarselDao: UnimplementedLegacyVarselDao,
    override val meldingDao: InMemoryMeldingDao,
    override val meldingDuplikatkontrollDao: NoopMeldingDuplikatkontrollDao,
    override val notatDao: DelegatingNotatDao,
    override val notatApiDao: UnimplementedNotatApiDao,
    override val oppgaveDao: DelegatingOppgaveDao,
    override val oppgaveApiDao: DelegatingOppgaveApiDao,
    override val oppgaveRepository: InMemoryOppgaveRepository,
    override val overstyringApiDao: UnimplementedOverstyringApiDao,
    override val periodehistorikkDao: InMemoryDoNothingPeriodehistorikkDao,
    override val periodehistorikkApiDao: UnimplementedPeriodehistorikkApiDao,
    override val personDao: DelegatingPersonDao,
    override val personApiDao: UnimplementedPersonApiDao,
    override val personinfoDao: UnimplementedPersoninfoDao,
    override val poisonPillDao: NoopPoisonPillDao,
    override val påVentDao: DelegatingPåVentDao,
    override val påVentApiDao: UnimplementedPåVentApiDao,
    override val reservasjonDao: InMemoryReservasjonDao,
    override val risikovurderingApiDao: UnimplementedRisikovurderingApiDao,
    override val saksbehandlerDao: DelegatingSaksbehandlerDao,
    override val saksbehandlerRepository: InMemorySaksbehandlerRepository,
    override val stansAutomatiskBehandlingDao: InMemoryStansAutomatiskBehandlingDao,
    override val stansAutomatiskBehandlingSaksbehandlerDao: UnimplementedStansAutomatiskBehandlingSaksbehandlerDao,
    override val tildelingDao: UnimplementedTildelingDao,
    override val tildelingApiDao: UnimplementedTildelingApiDao,
    override val varselApiRepository: UnimplementedVarselApiRepository,
    override val vedtakBegrunnelseDao: UnimplementedVedtakBegrunnelseDao,
    override val vedtakDao: UnimplementedVedtakDao,
    override val vergemålApiDao: UnimplementedVergemålApiDao,
) : Daos
