package no.nav.helse.spesialist.application.snapshot

enum class SnapshotBegrunnelse {
    ANDREYTELSER,
    EGENMELDINGUTENFORARBEIDSGIVERPERIODE,
    ETTERDODSDATO,
    MANGLERMEDLEMSKAP,
    MANGLEROPPTJENING,
    MINIMUMINNTEKT,
    MINIMUMINNTEKTOVER67,
    MINIMUMSYKDOMSGRAD,
    OVER70,
    SYKEPENGEDAGEROPPBRUKT,
    SYKEPENGEDAGEROPPBRUKTOVER67,
    __UNKNOWN_VALUE,
}
