package no.nav.helse.spesialist.application.snapshot

enum class SnapshotPeriodetilstand {
    ANNULLERINGFEILET,
    ANNULLERT,
    AVVENTERINNTEKTSOPPLYSNINGER,
    FORBEREDERGODKJENNING,
    INGENUTBETALING,
    MANGLERINFORMASJON,
    REVURDERINGFEILET,
    TILANNULLERING,
    TILGODKJENNING,
    TILINFOTRYGD,
    TILSKJONNSFASTSETTELSE,
    TILUTBETALING,
    UTBETALINGFEILET,
    UTBETALT,
    UTBETALTVENTERPAANNENPERIODE,
    VENTERPAANNENPERIODE,
    __UNKNOWN_VALUE,
}
