package no.nav.helse.db

import kotliquery.Session

class DBSessionContext(session: Session) : SessionContext {
    override val arbeidsforholdDao = PgArbeidsforholdDao(session)
    override val arbeidsgiverDao = PgArbeidsgiverDao(session)
    override val automatiseringDao = PgAutomatiseringDao(session)
    override val avviksvurderingDao = PgAvviksvurderingDao(session)
    override val commandContextDao = PgCommandContextDao(session)
    override val dialogDao = PgDialogDao(session)
    override val egenAnsattDao = PgEgenAnsattDao(session)
    override val generasjonDao = PgGenerasjonDao(session)
    override val inntektskilderRepository = PgInntektskilderRepository(session, arbeidsgiverDao, avviksvurderingDao)
    override val meldingDao = PgMeldingDao(session)
    override val metrikkDao = PgMetrikkDao(session)
    override val notatDao = PgNotatDao(session)
    override val oppgaveDao = PgOppgaveDao(session)
    override val opptegnelseRepository = PgOpptegnelseRepository(session)
    override val overstyringDao = PgOverstyringDao(session)
    override val periodehistorikkDao = PgPeriodehistorikkDao(session)
    override val personDao = PgPersonDao(session)
    override val påVentDao = PgPåVentDao(session)
    override val reservasjonDao = PgReservasjonDao(session)
    override val risikovurderingDao = PgRisikovurderingDao(session)
    override val saksbehandlerDao = PgSaksbehandlerDao(session)
    override val stansAutomatiskBehandlingDao = PgStansAutomatiskBehandlingDao(session)
    override val sykefraværstilfelleDao = PgSykefraværstilfelleDao(session)
    override val tildelingDao = PgTildelingDao(session)
    override val totrinnsvurderingDao = PgTotrinnsvurderingDao(session)
    override val utbetalingDao = PgUtbetalingDao(session)
    override val vedtakDao = PgVedtakDao(session)
    override val vergemålDao = PgVergemålDao(session)
    override val åpneGosysOppgaverDao = PgÅpneGosysOppgaverDao(session)
    override val vedtaksperiodeRepository = PgVedtaksperiodeRepository(generasjonDao, vedtakDao)
    override val personRepository = PgPersonRepository(vedtaksperiodeRepository, sykefraværstilfelleDao, avviksvurderingDao, personDao)
}
