package no.nav.helse.spesialist.api.oppgave

enum class Oppgavetype {
    SØKNAD, STIKKPRØVE, RISK_QA, REVURDERING, FORTROLIG_ADRESSE, UTBETALING_TIL_SYKMELDT, DELVIS_REFUSJON, UTBETALING_TIL_ARBEIDSGIVER, INGEN_UTBETALING
}
