INSERT INTO enhet (id, navn) VALUES (1169, 'NAV Rennesøy og Finnøy');
INSERT INTO enhet (id, navn) VALUES (1236, 'NAV Voss');
INSERT INTO enhet (id, navn) VALUES (1250, 'NAV Vaksdal');
INSERT INTO enhet (id, navn) VALUES (1783, 'NAV Værnes');
INSERT INTO enhet (id, navn) VALUES (5301, 'NAV Holmestrand');
INSERT INTO enhet (id, navn) VALUES (5302, 'NAV Færder');
INSERT INTO enhet (id, navn) VALUES (5303, 'NAV Larvik');
INSERT INTO enhet (id, navn) VALUES (5701, 'NAV Falkenborg');
INSERT INTO enhet (id, navn) VALUES (5702, 'NAV Lerkendal');
INSERT INTO enhet (id, navn) VALUES (5703, 'NAV Indre Fosen');
