ALTER TYPE utbetaling_status ADD VALUE 'AVVENTER_ARBEIDSGIVERKVITTERING';
ALTER TYPE utbetaling_status ADD VALUE 'AVVENTER_PERSONKVITTERING';
ALTER TYPE utbetaling_status ADD VALUE 'AVVENTER_KVITTERINGER';