DO
$$
    BEGIN
        IF EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'spesialist-db-migrations')
        THEN
            ALTER TABLE abonnement_for_opptegnelse
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE annullert_av_saksbehandler
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE api_varseldefinisjon
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE arbeidsforhold
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE arbeidsgiver
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE automatisering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE automatisering_korrigert_soknad
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE automatisering_problem
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE avviksvurdering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE avviksvurdering_spinnvillgate
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE begrunnelse
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE behandling
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE behandling_v2
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE command_context
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE dialog
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE dokumenter
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE egen_ansatt
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE enhet
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE flyway_schema_history
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE force_automatisering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE generasjon_begrunnelse_kobling
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE global_snapshot_versjon
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE gosysoppgaver
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE hendelse
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE infotrygdutbetalinger
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE inntekt
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE kommentarer
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE melding_duplikatkontroll
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE notat
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE oppdrag
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE oppgave
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE oppgave_behandling_kobling
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE opprinnelig_soknadsdato
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE opptegnelse
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_arbeidsforhold
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_dag
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_inntekt
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_minimum_sykdomsgrad
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_minimum_sykdomsgrad_arbeidsgiver
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_minimum_sykdomsgrad_periode
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_tidslinje
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyring_tilkommen_inntekt
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE overstyringer_for_vedtaksperioder
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE pa_vent
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE periodehistorikk
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE person
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE person_info
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE person_klargjores
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE poison_pill
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE reserver_person
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE risikovurdering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE risikovurdering_2021
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE risikovurdering_arbeidsuforhetvurdering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE risikovurdering_faresignal
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE saksbehandler
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE saksbehandler_opptegnelse_sekvensnummer
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE saksbehandleroppgavetype
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE sammenligningsgrunnlag
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE sammenligningsgrunnlag_spinnvillgate
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE selve_varsel
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE skjonnsfastsetting_sykepengegrunnlag
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE skjonnsfastsetting_sykepengegrunnlag_arbeidsgiver
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE snapshot
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE spesialsak
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE stans_automatisering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE stans_automatisk_behandling_saksbehandler
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE tildeling
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE tilkommen_inntekt_events
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE totrinnsvurdering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE utbetaling
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE utbetaling_id
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE utbetalingslinje
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vedtak
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vedtak_begrunnelse
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vedtaksperiode_hendelse
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vedtaksperiode_utbetaling_id
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vergemal
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vilkarsgrunnlag_per_avviksvurdering
                OWNER TO "spesialist-db-migrations";
            ALTER TABLE vilkarsgrunnlag_per_avviksvurdering_spinnvillgate
                OWNER TO "spesialist-db-migrations";
        END IF;
    END
$$;
