ALTER TABLE oppgave ALTER COLUMN type TYPE VARCHAR(64) USING RTRIM(type);
ALTER TABLE person_navn ALTER COLUMN fornavn TYPE VARCHAR(256) USING RTRIM(fornavn), ALTER COLUMN mellomnavn TYPE VARCHAR(256), ALTER COLUMN etternavn TYPE VARCHAR(256);
ALTER TABLE enhet ALTER COLUMN navn TYPE VARCHAR(256) USING RTRIM(navn);
ALTER TABLE person_egenskap_type ALTER COLUMN type TYPE VARCHAR(64) USING RTRIM(type);
