INSERT INTO enhet (id, navn) VALUES (100, 'NAV i Østfold');
INSERT INTO enhet (id, navn) VALUES (189, 'NAV Forvaltning Sarpsborg');
INSERT INTO enhet (id, navn) VALUES (200, 'NAV i Akershus');
INSERT INTO enhet (id, navn) VALUES (285, 'Oppgjørskontoret i Akershus');
INSERT INTO enhet (id, navn) VALUES (288, 'NAV Forvaltning Ski');
INSERT INTO enhet (id, navn) VALUES (289, 'NAV Forvaltning Lillestrøm');
INSERT INTO enhet (id, navn) VALUES (300, 'NAV i Oslo');
INSERT INTO enhet (id, navn) VALUES (312, 'Uranienborg-Majorstuen');
INSERT INTO enhet (id, navn) VALUES (313, 'St Hanshaugen-Ullevål');
INSERT INTO enhet (id, navn) VALUES (314, 'Sagene-Torshov');
INSERT INTO enhet (id, navn) VALUES (315, 'Grünerløkka-Sofienberg');
INSERT INTO enhet (id, navn) VALUES (316, 'Gamle Oslo');
INSERT INTO enhet (id, navn) VALUES (318, 'Ekeberg og Nordstrand');
INSERT INTO enhet (id, navn) VALUES (319, 'Søndre Nordstrand');
INSERT INTO enhet (id, navn) VALUES (321, 'Bøler og Østensjø');
INSERT INTO enhet (id, navn) VALUES (326, 'Furuset');
INSERT INTO enhet (id, navn) VALUES (327, 'Stovner');
INSERT INTO enhet (id, navn) VALUES (328, 'Grorud og Romsås');
INSERT INTO enhet (id, navn) VALUES (330, 'Bjerke');
INSERT INTO enhet (id, navn) VALUES (331, 'Kjelsås og Sogn');
INSERT INTO enhet (id, navn) VALUES (334, 'Røa');
INSERT INTO enhet (id, navn) VALUES (335, 'Ullern');
INSERT INTO enhet (id, navn) VALUES (349, 'Hjelpemiddelgruppa');
INSERT INTO enhet (id, navn) VALUES (366, 'Rikstrygdeverket');
INSERT INTO enhet (id, navn) VALUES (384, 'NAV Intro Oslo');
INSERT INTO enhet (id, navn) VALUES (385, 'Oppgjørskontoret i Oslo');
INSERT INTO enhet (id, navn) VALUES (389, 'NAV Forvaltning Oslo');
INSERT INTO enhet (id, navn) VALUES (391, 'NAV Arbeidslivssenter Oslo');
INSERT INTO enhet (id, navn) VALUES (396, 'NAV Arbeidsrådgivning Oslo');
INSERT INTO enhet (id, navn) VALUES (400, 'NAV i Hedmark');
INSERT INTO enhet (id, navn) VALUES (489, 'NAV Forvaltning Hamar');
INSERT INTO enhet (id, navn) VALUES (496, 'NAV Arbeidsrådgivning Hedmark');
INSERT INTO enhet (id, navn) VALUES (500, 'NAV i Oppland');
INSERT INTO enhet (id, navn) VALUES (589, 'NAV Forvaltning Lillehammer');
INSERT INTO enhet (id, navn) VALUES (591, 'NAV Arbeidslivssenter Oppland');
INSERT INTO enhet (id, navn) VALUES (600, 'NAV i Buskerud');
INSERT INTO enhet (id, navn) VALUES (689, 'NAV Forvaltning Buskerud');
INSERT INTO enhet (id, navn) VALUES (700, 'NAV i Vestfold');
INSERT INTO enhet (id, navn) VALUES (789, 'NAV Forvaltning Tønsberg');
INSERT INTO enhet (id, navn) VALUES (800, 'NAV i Telemark');
INSERT INTO enhet (id, navn) VALUES (889, 'NAV Forvaltning Skien');
INSERT INTO enhet (id, navn) VALUES (900, 'NAV i Aust-Agder');
INSERT INTO enhet (id, navn) VALUES (905, 'Grimstad ungdomskontor');
INSERT INTO enhet (id, navn) VALUES (989, 'NAV Forvaltning Arendal');
INSERT INTO enhet (id, navn) VALUES (1000, 'NAV i Vest-Agder');
INSERT INTO enhet (id, navn) VALUES (1084, 'NAV Intro Kristiansand');
INSERT INTO enhet (id, navn) VALUES (1089, 'NAV Forvaltning Vest-Agder');
INSERT INTO enhet (id, navn) VALUES (1091, 'NAV Arbeidslivssenter Vest-Agder');
INSERT INTO enhet (id, navn) VALUES (1096, 'NAV Arbeidsrådgivning Vest-Agder');
INSERT INTO enhet (id, navn) VALUES (1100, 'NAV i Rogaland');
INSERT INTO enhet (id, navn) VALUES (1161, 'Stavanger - Eiganes og Våland');
INSERT INTO enhet (id, navn) VALUES (1162, 'Stavanger - Hundvåg og Storhaug');
INSERT INTO enhet (id, navn) VALUES (1164, 'Stavanger - Hillevåg og Hinna');
INSERT INTO enhet (id, navn) VALUES (1165, 'Stavanger - Madla');
INSERT INTO enhet (id, navn) VALUES (1188, 'NAV Forvaltning Karmøy');
INSERT INTO enhet (id, navn) VALUES (1189, 'NAV Forvaltning Sandnes');
INSERT INTO enhet (id, navn) VALUES (1200, 'NAV i Hordaland');
INSERT INTO enhet (id, navn) VALUES (1202, 'Bergen - Fana');
INSERT INTO enhet (id, navn) VALUES (1203, 'Bergen - Åsane');
INSERT INTO enhet (id, navn) VALUES (1204, 'Bergen - Arna');
INSERT INTO enhet (id, navn) VALUES (1205, 'Bergen - Fyllingsdalen');
INSERT INTO enhet (id, navn) VALUES (1206, 'Bergen - Laksevåg');
INSERT INTO enhet (id, navn) VALUES (1208, 'Bergen - Årstad');
INSERT INTO enhet (id, navn) VALUES (1209, 'Bergen - Bergenhus');
INSERT INTO enhet (id, navn) VALUES (1210, 'Bergen - Ytrebygda');
INSERT INTO enhet (id, navn) VALUES (1288, 'NAV Forvaltning Stord');
INSERT INTO enhet (id, navn) VALUES (1289, 'NAV Forvaltning Bergen');
INSERT INTO enhet (id, navn) VALUES (1400, 'NAV i Sogn og Fjordane');
INSERT INTO enhet (id, navn) VALUES (1489, 'NAV Forvaltning Sogndal');
INSERT INTO enhet (id, navn) VALUES (1500, 'NAV i Møre og Romsdal');
INSERT INTO enhet (id, navn) VALUES (1589, 'NAV Forvaltning Molde');
INSERT INTO enhet (id, navn) VALUES (1600, 'NAV I Sør-Trøndelag');
INSERT INTO enhet (id, navn) VALUES (1603, 'Trondheim - Midtbyen');
INSERT INTO enhet (id, navn) VALUES (1604, 'Trondheim - Østbyen');
INSERT INTO enhet (id, navn) VALUES (1605, 'Trondheim - Lerkendal');
INSERT INTO enhet (id, navn) VALUES (1607, 'Trondheim - Heimdal');
INSERT INTO enhet (id, navn) VALUES (1688, 'NAV Forvaltning Orkdal');
INSERT INTO enhet (id, navn) VALUES (1689, 'NAV Forvaltning Trondheim');
INSERT INTO enhet (id, navn) VALUES (1700, 'NAV i Nord-Trøndelag');
INSERT INTO enhet (id, navn) VALUES (1789, 'NAV Forvaltning Levanger');
INSERT INTO enhet (id, navn) VALUES (1800, 'NAV i Nordland');
INSERT INTO enhet (id, navn) VALUES (1889, 'NAV Forvaltning Nordland');
INSERT INTO enhet (id, navn) VALUES (1900, 'NAV i Troms');
INSERT INTO enhet (id, navn) VALUES (1989, 'NAV Forvaltning Tromsø');
INSERT INTO enhet (id, navn) VALUES (2000, 'NAV i Finnmark');
INSERT INTO enhet (id, navn) VALUES (2089, 'NAV Forvaltning Vadsø');
INSERT INTO enhet (id, navn) VALUES (2101, 'NAV Internasjonalt');
INSERT INTO enhet (id, navn) VALUES (2103, 'NAV Viken');
INSERT INTO enhet (id, navn) VALUES (2310, 'Region Oslo');
INSERT INTO enhet (id, navn) VALUES (2320, 'Region Øst - Fredrikstad');
INSERT INTO enhet (id, navn) VALUES (2330, 'Region Sør - Tønsberg');
INSERT INTO enhet (id, navn) VALUES (2340, 'Region Vest - Hillevåg');
INSERT INTO enhet (id, navn) VALUES (2350, 'Region Midt - Ørsta');
INSERT INTO enhet (id, navn) VALUES (2360, 'Region Nord - Mo i Rana');
INSERT INTO enhet (id, navn) VALUES (2890, 'NAV Modernisering');
INSERT INTO enhet (id, navn) VALUES (3010, 'HMS i Østfold');
INSERT INTO enhet (id, navn) VALUES (3060, 'HMS i Buskerud');
INSERT INTO enhet (id, navn) VALUES (3070, 'HMS i Vestfold');
INSERT INTO enhet (id, navn) VALUES (3080, 'HMS i Telemark');
INSERT INTO enhet (id, navn) VALUES (3090, 'HMS i Aust-Agder');
INSERT INTO enhet (id, navn) VALUES (3100, 'HMS i Vest-Agder');
INSERT INTO enhet (id, navn) VALUES (3110, 'HMS i Rogaland');
INSERT INTO enhet (id, navn) VALUES (3120, 'HMS i Hordaland');
INSERT INTO enhet (id, navn) VALUES (3140, 'HMS i Sogn og Fjordane');
INSERT INTO enhet (id, navn) VALUES (3150, 'HMS i Møre og Romsdal');
INSERT INTO enhet (id, navn) VALUES (3160, 'HMS i Sør-Trøndelag');
INSERT INTO enhet (id, navn) VALUES (3170, 'HMS i Nord-Trøndelag');
INSERT INTO enhet (id, navn) VALUES (3180, 'HMS i Nordland');
INSERT INTO enhet (id, navn) VALUES (3190, 'HMS i Troms');
INSERT INTO enhet (id, navn) VALUES (3200, 'HMS i Finnmark');
INSERT INTO enhet (id, navn) VALUES (4100, 'NAV Styringsenhet Kontaktsenter');
INSERT INTO enhet (id, navn) VALUES (4103, 'NAV Kontaktsenter Oslo og Akershus');
INSERT INTO enhet (id, navn) VALUES (4108, 'NAV Kontaktsenter Telemark');
INSERT INTO enhet (id, navn) VALUES (4109, 'NAV Kontaktsenter Aust-Agder');
INSERT INTO enhet (id, navn) VALUES (4110, 'NAV Kontaktsenter Vest-Agder');
INSERT INTO enhet (id, navn) VALUES (4115, 'NAV Kontaktsenter Møre og Romsdal');
INSERT INTO enhet (id, navn) VALUES (4116, 'NAV Kontaktsenter Sør-Trøndelag');
INSERT INTO enhet (id, navn) VALUES (4119, 'NAV Kontaktsenter Troms');
INSERT INTO enhet (id, navn) VALUES (4534, 'NAV AA-registeret');
INSERT INTO enhet (id, navn) VALUES (4540, 'NAV Sentralt Yrkessykdomskontor');
INSERT INTO enhet (id, navn) VALUES (4550, 'NAV Registerkontroll Oslo');
INSERT INTO enhet (id, navn) VALUES (4560, 'NAV Registerkontroll Vågå');
