name: Deploy alerts
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main-alerts.yml'
      - 'deploy/alerts/**.yml'

jobs:
  apply-alerts:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/alerts/alertconfig.yml,deploy/alerts/prod-alerts.yml
