name: Bygg og deploy main

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 3'
      timezone: 'Europe/Oslo'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bygg-og-test:
    name: Bygg og test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write # for dependency graph
      id-token: write # for nais login
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: NAIS login
        id: login
        uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
        with:
          team: tbd

      - name: gradlew clean build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew clean build --build-cache

      - name: gradlew jib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew jib --build-cache \
            -Pimage.registry='${{ steps.login.outputs.registry }}' \
            -Pimage.tag=$(date -u +%Y.%m.%d-%H.%M)-$(git rev-parse --short=12 HEAD) \
            -Djib.console=plain

      - name: Last opp jib-metadata
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jib-metadata
          path: '**/build/jib-image.*'
          if-no-files-found: error
          retention-days: 1

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  les-deploy-matrix:
    name: Les deploy-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Les .github/deploy-matrix.json
        id: les-deploy-matrix
        run: echo "deploy-matrix=$(jq -c . .github/deploy-matrix.json)" >> "$GITHUB_OUTPUT"
    outputs:
      deploy-matrix: ${{ steps.les-deploy-matrix.outputs.deploy-matrix }}

  deploy:
    name: Deploy ${{ matrix.module }}
    needs: [bygg-og-test, les-deploy-matrix]
    permissions:
      actions: read # for sarif
      contents: write # for sarif
      security-events: write # push sarif to github security
      id-token: write # for nais login
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.les-deploy-matrix.outputs.deploy-matrix) }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Last ned jib-metadata
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: jib-metadata

      - name: Beregn image-referanse
        id: image
        run: |
          set -euo pipefail
          ref="$(cat '${{ matrix.module }}/build/jib-image.name')@$(cat '${{ matrix.module }}/build/jib-image.digest')"
          echo "ref=$ref" >> "$GITHUB_OUTPUT"

      - name: NAIS login
        uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
        with:
          team: tbd

      - name: Generer SBOM, attester og signer
        uses: nais/attest-sign@bb00e4baa4e7acd00b6aff2502b2dfed3d4fad40 # v2
        with:
          image_ref: ${{ steps.image.outputs.ref }}

      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ steps.image.outputs.ref }}
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'

      - uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          sarif_file: 'trivy.sarif'

      - name: Deploy til dev
        if: ${{ !matrix.dev.disabled }}
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ${{ matrix.dev.resource }}
          VARS: ${{ matrix.dev.vars || '/dev/null' }}
          WORKLOAD_IMAGE: ${{ steps.image.outputs.ref }}

      - name: Deploy til prod
        if: ${{ !matrix.prod.disabled }}
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: ${{ matrix.prod.resource }}
          VARS: ${{ matrix.prod.vars || '/dev/null' }}
          WORKLOAD_IMAGE: ${{ steps.image.outputs.ref }}
