name: Spesialist-opprydding-dev

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-opprydding-dev'
      - 'spesialist-opprydding-dev/**'
      - 'build.gradle.kts'
      - 'gradle/libs.versions.toml'
      - '.github/workflows/spesialist-opprydding-dev.yml'
      - '.github/workflows/build-image.yml'
      - 'deploy/dev-opprydding.yml'
      - 'deploy/dev-db-policy.yml'
      - '.dockerignore'
  schedule:
    - cron: '0 4 * * 3'
      timezone: 'Europe/Oslo'

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      gradle_command: :spesialist-opprydding-dev:installDist
      dockerfile: Dockerfile-opprydding-dev
      image_suffix: opprydding-dev
    secrets: inherit

  deployDev:
    name: deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev-opprydding.yml
          IMAGE: ${{ needs.build.outputs.image }}
