name: Spesialist-sidegig

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-sidegig'
      - 'spesialist-sidegig/**'
      - 'build.gradle.kts'
      - 'gradle/libs.versions.toml'
      - '.github/workflows/spesialist-sidegig.yml'
      - 'deploy/prod-sidegig.yml'
      - 'deploy/prod-db-policy.yml'
      - '.dockerignore'

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: navikt/helse-spesialist/.github/workflows/build-image.yml@main
    with:
      gradle_command: :spesialist-sidegig:build
      dockerfile: Dockerfile-sidegig
      image_suffix: sidegig
    secrets: inherit

  deployDev:
    name: deploy to prod
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod-sidegig.yml
          IMAGE: ${{ needs.build.outputs.image }}
