name: Spesialist-DB-migrations

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile-db-migrations'
      - 'spesialist-db-migrations/**'
      - '.github/workflows/spesialist-db-migrations.yml'
      - '.github/workflows/build-image.yml'
      - 'deploy/dev-db-migrations.yml'
      - 'deploy/prod-db-migrations.yml'
      - '.dockerignore'

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      module: spesialist-db-migrations
      dockerfile: Dockerfile-db-migrations
      image_suffix: db-migrations
    secrets: inherit

  deployDev:
    name: deploy to dev
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev-db-migrations.yml
          IMAGE: ${{ needs.build.outputs.image }}

  deployProd:
    name: deploy to prod
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod-db-migrations.yml
          IMAGE: ${{ needs.build.outputs.image }}
