package no.nav.helse.spesialist.api.abonnement

enum class OpptegnelseType {
    UTBETALING_ANNULLERING_FEILET,
    UTBETALING_ANNULLERING_OK,
    FERDIGBEHANDLET_GODKJENNINGSBEHOV,
    NY_SAKSBEHANDLEROPPGAVE,
    REVURDERING_AVVIST,
    REVURDERING_FERDIGBEHANDLET,
    PERSONDATA_OPPDATERT,
}
